theme: jekyll-theme-slate
title: WP Simplified Comment Auto Moderation Plugin
description: If comment author's email found with already approved comment, the comment will be approved even if the author's name differs.